services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-proot",  "ping", "-h", "localhost"]
      interval: 30s
      timeout: 20s
      retries: 10
  myapp:
    container_name: spigot
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    build: .
    networks:
      - app-network
    ports:
      - "25565:25565"

networks:
  app-network:
    driver: bridge